spring:
    datasource:
        name: dev
        url: jdbc:mysql://192.168.1.6:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&logger=com.mysql.jdbc.log.Slf4JLogger&profileSQL=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    data:
        mongodb:
             uri: mongodb://qa.vm.com:20177/wxbMongoDB
    rabbitmq:
        host: qa.vm.com
        username: 10bei
        password: 10bei.cn
        virtual-host: /10bei
        publisher-confirms: true
mybatis:
    mapperLocations: classpath:com.feivirus.springbootstudy.dao/*.xml
    typeAliasesPackage: tk.mapper.model

#redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 3000
#    jedis:
#        pool:
#            max-idle: 500
#            min-idle: 50
#            max-active: 2000
#            max-wait: 1000
#    testOnBorrow: true
