package com.feivirus.redpacket.dao;

import com.feivirus.redpacket.domain.RedPackets;
import com.feivirus.redpacket.domain.RedPacketsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RedPacketsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    long countByExample(RedPacketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int deleteByExample(RedPacketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int insert(RedPackets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int insertSelective(RedPackets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    List<RedPackets> selectByExample(RedPacketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    RedPackets selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RedPackets record, @Param("example") RedPacketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RedPackets record, @Param("example") RedPacketsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RedPackets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packets
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RedPackets record);
}