package com.feivirus.redpacket.dao;

import com.feivirus.redpacket.domain.RpRecords;
import com.feivirus.redpacket.domain.RpRecordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RpRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    long countByExample(RpRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int deleteByExample(RpRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int insert(RpRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int insertSelective(RpRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    List<RpRecords> selectByExample(RpRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    RpRecords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RpRecords record, @Param("example") RpRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RpRecords record, @Param("example") RpRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RpRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RpRecords record);
}