package com.feivirus.orderpay.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_pay_apply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class PayApply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_apply.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_apply.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   支付流水号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_apply.pay_serial_number
     *
     * @mbg.generated
     */
    private String paySerialNumber;

    /**
     * Database Column Remarks:
     *   处理状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_apply.process_status
     *
     * @mbg.generated
     */
    private Integer processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_pay_apply.id
     *
     * @return the getValue of t_pay_apply.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_pay_apply.id
     *
     * @param id the getValue for t_pay_apply.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_pay_apply.order_id
     *
     * @return the getValue of t_pay_apply.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_pay_apply.order_id
     *
     * @param orderId the getValue for t_pay_apply.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_pay_apply.pay_serial_number
     *
     * @return the getValue of t_pay_apply.pay_serial_number
     *
     * @mbg.generated
     */
    public String getPaySerialNumber() {
        return paySerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_pay_apply.pay_serial_number
     *
     * @param paySerialNumber the getValue for t_pay_apply.pay_serial_number
     *
     * @mbg.generated
     */
    public void setPaySerialNumber(String paySerialNumber) {
        this.paySerialNumber = paySerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_pay_apply.process_status
     *
     * @return the getValue of t_pay_apply.process_status
     *
     * @mbg.generated
     */
    public Integer getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_pay_apply.process_status
     *
     * @param processStatus the getValue for t_pay_apply.process_status
     *
     * @mbg.generated
     */
    public void setProcessStatus(Integer processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", paySerialNumber=").append(paySerialNumber);
        sb.append(", processStatus=").append(processStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}