package com.feivirus.orderpay.dao;

import com.feivirus.orderpay.domain.PayApply;
import com.feivirus.orderpay.domain.PayApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    long countByExample(PayApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int deleteByExample(PayApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int insert(PayApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int insertSelective(PayApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    List<PayApply> selectByExample(PayApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    PayApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayApply record, @Param("example") PayApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayApply record, @Param("example") PayApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayApply record);
}