package com.feivirus.redpacket.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_rp_records
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RpRecords implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rp_records.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   红包id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rp_records.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     * Database Column Remarks:
     *   用户id,t_user_account表uid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rp_records.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   红包金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rp_records.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rp_records.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_rp_records.id
     *
     * @return the getValue of t_rp_records.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_rp_records.id
     *
     * @param id the getValue for t_rp_records.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_rp_records.rid
     *
     * @return the getValue of t_rp_records.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_rp_records.rid
     *
     * @param rid the getValue for t_rp_records.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_rp_records.uid
     *
     * @return the getValue of t_rp_records.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_rp_records.uid
     *
     * @param uid the getValue for t_rp_records.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_rp_records.amount
     *
     * @return the getValue of t_rp_records.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_rp_records.amount
     *
     * @param amount the getValue for t_rp_records.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the getValue of the database column t_rp_records.add_time
     *
     * @return the getValue of t_rp_records.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the getValue of the database column t_rp_records.add_time
     *
     * @param addTime the getValue for t_rp_records.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rp_records
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rid=").append(rid);
        sb.append(", uid=").append(uid);
        sb.append(", amount=").append(amount);
        sb.append(", addTime=").append(addTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}